# Generated by Django 4.1.6 on 2023-02-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p1',
            name='image',
            field=models.ImageField(default='hello', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
