# Generated by Django 4.1.6 on 2023-02-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1app', '0002_p1_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p1',
            old_name='image',
            new_name='img',
        ),
    ]
