# Generated by Django 4.1.6 on 2023-02-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1app', '0003_rename_image_p1_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='p1',
            new_name='movies',
        ),
    ]
